version: '3.9'
services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - mongodb.env
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    ports: 
      - 8081:8081
    env_file: mongo-express.env
